default: &default
  adapter: postgis
  encoding: unicode
  postgis_extension: postgis
  postgis_schema: public
  schema_search_path: public,postgis
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: geojson_rails_postgres_development

test:
  <<: *default
  database: geojson_rails_postgres_test

production:
  <<: *default
  database: geojson_rails_postgres_production
  username: geojson_rails_postgres
  password: <%= ENV['GEOJSON_RAILS_POSTGRES_DATABASE_PASSWORD'] %>
